version: 2
jobs:
  build:
    docker:
      - image: danieluranga/leela_chess_zero-lc0_ubuntu_builder:0.0.4
    steps:
      - checkout
      - run:
          name: "Pull Submodules"
          command: |
            git submodule init
            git submodule update --remote
      - run:
          name: Build clang version
          command: CC=clang-6.0 CXX=clang++-6.0 ./build.sh
      - run:
          command: cp build/release/lc0 /tmp/lc0-clang
      - run:
          name: Build g++ version
          command: ./build.sh
      - run:
          command: cp build/release/lc0 /tmp/lc0-g++
      - store_artifacts:
          path: /tmp/lc0-clang
          destination: lc0-ubuntu-18-04-clang
      - store_artifacts:
          path: /tmp/lc0-g++
          destination: lc0-ubuntu-18-04-g++
